post/urls.py
from django.conf.urls import url

from post import views


urlpatterns = (
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetail.as_view(), name='post'),
    url(r'^post/(?P<pk>[0-9]+)/like/$', views.LikeState.as_view(),
        name='like'),
    url(r'^post/(?P<pk>[0-9]+)/comment/$', views.CreateComment.as_view(),
        name='comment'),
    url(r'^post/make/$', views.CreatePost.as_view(), name='make'),
    url(r'^$', views.PostList.as_view(), name='list')
)

test_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^authentication/', include('user.urls', namespace='auth')),
    url(r'^', include('post.urls', namespace='post'))
]

templates/comment/comment_list.html
<h4> Comments ({{ comment_list|length }}):</h4>
<form action="{% url 'post:comment' post.pk %}" method="post" name="comment_form">
    {% csrf_token %}
    <textarea rows="5" cols="40" name="comment_text" placeholder="Write your comment here..."></textarea>
    <br>
    <input type="submit" value="Comment" />
</form>
{% if comment_list %}
    <ul>
    {% for comment in comment_list %}
        <li>
            {{ comment.author }}
            {{ comment.date }}
            {{ comment.text }}
        </li>
    {% endfor %}
    </ul>
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% else %}
    <p>No comments yet.</p>
{% endif %}