post/urls.py
from django.conf.urls import url

from post import views


urlpatterns = (
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetail.as_view(), name='post'),
    url(r'^post/(?P<pk>[0-9]+)/like/$', views.LikeState.as_view(),
        name='like'),
    url(r'^post/(?P<pk>[0-9]+)/comment/$', views.CreateComment.as_view(),
        name='comment'),
    url(r'^post/make/$', views.CreatePost.as_view(), name='make'),
    url(r'^$', views.PostList.as_view(), name='list')
)

test_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^authentication/', include('user.urls', namespace='auth')),
    url(r'^', include('post.urls', namespace='post'))
]

user/urls.py
from django.conf.urls import url
from user import views


urlpatterns = (
    url(r'^sign_up$', views.SignUp.as_view(), name='sign_up'),
    url(r'^sign_in$',views.SignIn.as_view(), name='sign_in_page'),
    url(r'^sign_out$', views.SignOut.as_view(), name='sign_out'),
    url(r'^activate/(?P<uid_b64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.Activate.as_view(), name='activate'),
)

templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'auth:activate' uid_b64=uid token=token %}
{% endautoescape %}

templates/base.html
<!DOCTYPE HTML>
<head>
    <title>
        {% block title %}Test-project{% endblock %}
    </title>
</head>
<body>
    <div id="header">
        <a href="/">Test-project</a>
        {%  if request.user.is_active %}
        <a href="/post/make/">
            <input type="button" value="Make a post">
        </a>
        {% endif %}
        {% if request.user.is_authenticated %}
        <a href="{% url 'auth:sign_out' %}" style="float: right;">
            <input type="button" value="Sign Out">
        </a>
        <p style="float: right;">{{ request.user}}</p>
        {% else %}
        <a href="{% url 'auth:sign_in_page' %}" style="float: right;">
            <input type="button" value="Sign In">
        </a>
        <a href="{% url 'auth:sign_up' %}" style="float: right;">
            <input type="button" value="Sign Up">
        </a>
        {% endif %}
    </div>
    <div>
        <br>
        {% block content %}{% endblock %}
    </div>
</body>

templates/signup.html
{% extends 'base.html' %}
{% block content %}
<h2>{% if action %}{{ action }}{% else %}Sign up{% endif %}</h2>

<form method="post">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
        <small style="color: red">{{ error }}</small><br>
    {% endfor %}
    {% for field in form %}
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
            <small style="color: red">{{ error }}</small>
        {% endfor %}<br>
        {% if field.help_text %}
            <small style="display: none">{{ field.help_text }}</small>
        {% endif %}
    {% endfor %}
    <br>
    <button type="submit">{% if action %}{{ action }}{% else %}Sign up{% endif %}</button>
</form>
{% endblock %}