post/urls.py
from django.conf.urls import url

from post import views


urlpatterns = (
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetail.as_view(), name='post'),
    url(r'^post/(?P<pk>[0-9]+)/like/$', views.LikeState.as_view(),
        name='like'),
    url(r'^post/(?P<pk>[0-9]+)/comment/$', views.CreateComment.as_view(),
        name='comment'),
    url(r'^post/make/$', views.CreatePost.as_view(), name='make'),
    url(r'^$', views.PostList.as_view(), name='list')
)

test_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^authentication/', include('user.urls', namespace='auth')),
    url(r'^', include('post.urls', namespace='post'))
]

post/models.py
from django.contrib.auth import get_user_model
from django.db import models


class PostManager(models.Manager):
    def new(self):
        return self.order_by('-date')


class Post(models.Model):
    objects = PostManager()
    author = models.ForeignKey(get_user_model(), blank=False, null=False)
    title = models.CharField(max_length=200, blank=False, null=False)
    body = models.TextField(blank=False, null=False)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def like_from_user(self, user):
        return self.likes.filter(author=user, state=True).last()


class Comment(models.Model):
    author = models.ForeignKey(get_user_model(), blank=False, null=False)
    post = models.ForeignKey(Post, blank=False, null=False)
    text = models.TextField(blank=False, null=False)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class LikeManager(models.Manager):
    def active(self):
        return self.filter(state=True)


class Like(models.Model):
    objects = LikeManager()
    author = models.ForeignKey(get_user_model(), blank=False, null=False)
    state = models.BooleanField(default=True)
    post = models.ForeignKey(
        Post,
        related_name='likes',
        blank=False,
        null=False
    )

    def change_state(self):
        self.state = False if self.state else True
        self.save()

post/views.py
from django.contrib.auth import get_user_model
from django.core.paginator import EmptyPage
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic, View
from django.utils.translation import ugettext as _

from post.models import Post, Like, Comment


class PostList(generic.ListView):
    model = Post
    queryset = Post.objects.new()
    paginate_by = 5
    context_object_name = 'post_list'

    def paginate_queryset(self, queryset, page_size):
        """
        Overrides `MultipleObjectMixin.paginate_queryset`
        to solve EmptyPage problem
        """
        paginator = self.get_paginator(queryset, page_size)
        page_kwarg = self.page_kwarg
        page = (self.kwargs.get(page_kwarg) or
                self.request.GET.get(page_kwarg) or 1)
        try:
            page_number = int(page)
        except ValueError:
            raise Http404(_("Page can not be converted to an int."))
        try:
            page = paginator.page(page_number)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
        finally:
            return paginator, page, page.object_list, page.has_other_pages()


class PostDetail(generic.DetailView):
    model = Post
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = context.get('post')
        context['comment_list'] = post.comment_set.all()
        context['like'] = post.like_from_user(self.request.user)
        return context


class CreatePost(generic.CreateView):
    model = Post
    fields = ['title', 'body']
    template_name = 'post/create.html'
    success_url = '/'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        user_model = get_user_model()
        self.object.author = user_model.objects.get(pk=self.request.user.pk)
        return super().form_valid(form)


class CreateComment(View):
    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        text = request.POST.get('comment_text')
        Comment.objects.create(text=text, post=post, author=request.user)
        return HttpResponseRedirect(
            reverse('post:post', kwargs={'pk': post.id})
        )


class LikeState(View):

    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        author = request.user
        like, created = Like.objects.get_or_create(author=author, post=post)
        if not created:
            like.change_state()
        return HttpResponseRedirect(
            reverse('post:post', kwargs={'pk': post.id})
        )

templates/post/create.html
<!DOCTYPE HTML>
{% extends 'base.html' %}
{% block content %}
    <form method="post">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
        <small style="color: red">{{ error }}</small><br>
    {% endfor %}
    {% for field in form %}
        {{ field.label_tag }}<br>
        {{ field }}
        {% for error in field.errors %}
            <small style="color: red">{{ error }}</small>
        {% endfor %}<br>
    {% if field.help_text %}
        <small style="display: none">{{ field.help_text }}</small>
    {% endif %}
    {% endfor %}
    <br>
    <button type="submit">Post</button>
</form>
{% endblock %}

templates/post/post_detail.html
<!DOCTYPE HTML>
{% extends 'base.html' %}
{% block content %}
<h1>{{ post.title }}</h1>

<p>
    {{ post.body }}
    <br>
    <br>{{ post.date }}
    <br>{{ post.author }}
</p>
    <form action="{% url 'post:like' post.id%}" method="post" >
        {% csrf_token %}
        <input type="submit" value="{% if like %} Unlike {% else %} Like {% endif %}({{ post.likes.active|length }})" />
    </form>
    {% include 'comment/comment_list.html' %}
{% endblock %}

templates/post/post_list.html
<!DOCTYPE HTML>
{% extends 'base.html' %}
{% block title %}
    Main Page
{% endblock %}

{% block content %}
{% for post in post_list %}
    <br>
    <fieldset>
        <legend>
            <h4>
                <a href="{% url 'post:post' post.id %}">{{ post.title }}</a>
                {% if request.user == post.author %}
                    by You
                {% else %}
                    by {{ post.author }}
                {% endif %}
                | {{ post.date }}
            </h4>
        </legend>

    {{ post.body }}
    </fieldset>
    <br>



{% endfor %}
{% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}